export const MASTER_UGC_PROMPT = `Hyper-realistic paused-frame screenshot from an authentic TikTok selfie video. The image should look like a random frame captured mid-video on a front-facing iPhone camera—not posed, not polished, not staged.
A normal attractive woman in her mid-20s to early 30s casually shows or uses [PRODUCT] as part of her real daily routine. She should look relatable and naturally pretty, not like a model or influencer. Minimal makeup or bare skin, natural skin texture, subtle imperfections like slight under-eye shadows, mild redness or flushed cheeks, realistic pores, and imperfect teeth/smile if visible. Hair should look air-dried, slightly messy, or casually tucked behind one ear—not styled.
The framing should feel accidental and imperfect: awkward close crop, forehead partially cut off or product partially off-center, hand too close to lens, slightly weird angle, casual paused-while-talking composition.
Expression should feel natural: soft smile, mid-sentence mouth open, candid laugh, focused on the product, casual eye contact with camera.
Lighting should be realistic and imperfect: uneven natural daylight from a nearby window, slightly blown-out highlights, mild shadows on one side of the face, indoor home lighting mixed with daylight, bad but believable lighting.
Environment should feel lived-in and authentic: real kitchen, messy bathroom counter, patio, bedroom, car, cluttered countertop, normal home background slightly blurred naturally.
The [PRODUCT] should appear naturally in the scene: held casually, partially blurred in foreground, on counter in background, being used in action, visible and readable but not aggressively staged.
Camera aesthetic: front-facing iPhone selfie camera, slight motion blur, subtle grain, mild compression artifacts, realistic digital softness, no DSLR look, no cinematic depth of field, no over-sharpening.
Color/edit style: natural colors, slightly muted, realistic white balance, no over-saturation, no aesthetic filter, no orange/teal grading, no luxury polished tones.
AVOID: No CGI. No beauty filter. No influencer aesthetic. No studio lighting. No perfect symmetry. No polished composition. No glamour makeup. No fake skin. No waxy skin. No fake teeth. No fake fingers. No impossible reflections. No luxury/editorial vibe. No stock-photo smile. No AI pretty girl. No TikTok UI. No Instagram UI. No social media overlays. No platform interface elements. No text overlays. No subtitle bars. No comment bubbles. No like buttons. No username text. No hashtags overlaid on image.
GOAL: The image must feel like an accidental paused frame from a real TikTok video that organically got millions of views.`

export const SAL_CELTICA_PRODUCT = `the exact Sal Céltica Marina Fina product bag from the reference image provided — a blue and white illustrated standup pouch with 'SAL CÉLTICA MARINA Fina' text prominently on front, Nature's Blessings logo at top, salt harvester illustration in center, certification badges at bottom. The EXACT packaging design must be preserved and clearly visible. Do not alter the packaging design, colors, or labels in any way.`
